[package]
name = 'jsfader-rs'
version = '0.1.0'
authors = ['l0calh05t <l0calh05t@gmx.net>']
license = 'Apache-2.0'
edition = '2018'

[lib]
name = 'jsFaderRust'
crate-type = ['cdylib']

[dependencies]
itertools-num = '0.1.3'
lazy_static = '1.4.0'
num-traits = '0.2.12'
vst = '0.2.0'
